package edu.rsvier.springmvc.model;
// Generated 29-apr-2015 14:52:58 by Hibernate Tools 4.3.1

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bestand generated by hbm2java
 */
@Entity
@Table(name = "bestand", catalog = "cursisttraject_relatiebeheer"
)
public class Bestand implements java.io.Serializable {

    private int id;
    private byte[] bestand;
    private Set<Materiaal> materialen = new HashSet<Materiaal>(0);
    private Set<Toets> toetsen = new HashSet<Toets>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "bestand", nullable = false)
    public byte[] getBestand() {
        return this.bestand;
    }

    public void setBestand(byte[] bestand) {
        this.bestand = bestand;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bestand", cascade = {CascadeType.REFRESH, CascadeType.MERGE, CascadeType.PERSIST})
    public Set<Materiaal> getMaterialen() {
        return this.materialen;
    }

    public void setMaterialen(Set<Materiaal> materialen) {
        this.materialen = materialen;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bestand", cascade = {CascadeType.REFRESH, CascadeType.MERGE, CascadeType.PERSIST})
    public Set<Toets> getToetsen() {
        return this.toetsen;
    }

    public void setToetsen(Set<Toets> toetsen) {
        this.toetsen = toetsen;
    }

    public String toString() {
        return ("Bestand: " + id);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Bestand other = (Bestand) obj;
        if (this.id != other.id) {
            return false;
        }
        if (!Arrays.equals(this.bestand, other.bestand)) {
            return false;
        }
        if (this.materialen != other.materialen && (this.materialen == null || !this.materialen.equals(other.materialen))) {
            return false;
        }
        if (this.toetsen != other.toetsen && (this.toetsen == null || !this.toetsen.equals(other.toetsen))) {
            return false;
        }
        return true;
    }



}
