//package edu.rsvier.springmvc.model;
//// Generated May 11, 2015 11:42:12 AM by Hibernate Tools 4.3.1
//
//import javax.persistence.AttributeOverride;
//import javax.persistence.AttributeOverrides;
//import javax.persistence.Column;
//import javax.persistence.EmbeddedId;
//import javax.persistence.Entity;
//import javax.persistence.Table;
//
///**
// * MateriaalHasModule generated by hbm2java
// */
//@Entity
//@Table(name = "materiaal_has_module", catalog = "cursisttraject_relatiebeheer")
//public class MateriaalHasModule implements java.io.Serializable {
//
//    private MateriaalHasModuleId id;
//
//    public MateriaalHasModule() {
//    }
//
//    public MateriaalHasModule(MateriaalHasModuleId id) {
//        this.id = id;
//    }
//
//    @EmbeddedId
//
//    @AttributeOverrides({
//        @AttributeOverride(name = "materiaalId", column = @Column(name = "materiaal_id", nullable = false)),
//        @AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false))})
//    public MateriaalHasModuleId getId() {
//        return this.id;
//    }
//
//    public void setId(MateriaalHasModuleId id) {
//        this.id = id;
//    }
//
//}
