//package edu.rsvier.springmvc.model;
//// Generated May 11, 2015 11:42:12 AM by Hibernate Tools 4.3.1
//
//
//import javax.persistence.Column;
//import javax.persistence.Embeddable;
//
///**
// * MateriaalHasModuleId generated by hbm2java
// */
//@Embeddable
//public class MateriaalHasModuleId  implements java.io.Serializable {
//
//
//     private int materiaalId;
//     private int moduleId;
//
//    public MateriaalHasModuleId() {
//    }
//
//    public MateriaalHasModuleId(int materiaalId, int moduleId) {
//       this.materiaalId = materiaalId;
//       this.moduleId = moduleId;
//    }
//   
//
//
//    @Column(name="materiaal_id", nullable=false)
//    public int getMateriaalId() {
//        return this.materiaalId;
//    }
//    
//    public void setMateriaalId(int materiaalId) {
//        this.materiaalId = materiaalId;
//    }
//
//
//    @Column(name="module_id", nullable=false)
//    public int getModuleId() {
//        return this.moduleId;
//    }
//    
//    public void setModuleId(int moduleId) {
//        this.moduleId = moduleId;
//    }
//
//
//   public boolean equals(Object other) {
//         if ( (this == other ) ) return true;
//		 if ( (other == null ) ) return false;
//		 if ( !(other instanceof MateriaalHasModuleId) ) return false;
//		 MateriaalHasModuleId castOther = ( MateriaalHasModuleId ) other; 
//         
//		 return (this.getMateriaalId()==castOther.getMateriaalId())
// && (this.getModuleId()==castOther.getModuleId());
//   }
//   
//   public int hashCode() {
//         int result = 17;
//         
//         result = 37 * result + this.getMateriaalId();
//         result = 37 * result + this.getModuleId();
//         return result;
//   }   
//
//
//}
//
//
