//package edu.rsvier.springmvc.model;
//// Generated May 11, 2015 11:42:12 AM by Hibernate Tools 4.3.1
//
//
//import javax.persistence.AttributeOverride;
//import javax.persistence.AttributeOverrides;
//import javax.persistence.Column;
//import javax.persistence.EmbeddedId;
//import javax.persistence.Entity;
//import javax.persistence.Table;
//
///**
// * PersoonsrolHasMateriaal generated by hbm2java
// */
//@Entity
//@Table(name="persoonsrol_has_materiaal"
//    ,catalog="cursisttraject_relatiebeheer"
//)
//public class PersoonsrolHasMateriaal  implements java.io.Serializable {
//
//
//     private PersoonsrolHasMateriaalId id;
//     private Character cursistBezit;
//
//    public PersoonsrolHasMateriaal() {
//    }
//
//	
//    public PersoonsrolHasMateriaal(PersoonsrolHasMateriaalId id) {
//        this.id = id;
//    }
//    public PersoonsrolHasMateriaal(PersoonsrolHasMateriaalId id, Character cursistBezit) {
//       this.id = id;
//       this.cursistBezit = cursistBezit;
//    }
//   
//     @EmbeddedId
//
//    
//    @AttributeOverrides( {
//        @AttributeOverride(name="persoonsrolPersoonId", column=@Column(name="persoonsrol_persoon_id", nullable=false) ), 
//        @AttributeOverride(name="persoonsrolRolId", column=@Column(name="persoonsrol_rol_id", nullable=false) ), 
//        @AttributeOverride(name="persoonsrolBegindatum", column=@Column(name="persoonsrol_begindatum", nullable=false, length=10) ), 
//        @AttributeOverride(name="materiaalId", column=@Column(name="materiaal_id", nullable=false) ) } )
//    public PersoonsrolHasMateriaalId getId() {
//        return this.id;
//    }
//    
//    public void setId(PersoonsrolHasMateriaalId id) {
//        this.id = id;
//    }
//
//    
//    @Column(name="cursist_bezit", length=1)
//    public Character getCursistBezit() {
//        return this.cursistBezit;
//    }
//    
//    public void setCursistBezit(Character cursistBezit) {
//        this.cursistBezit = cursistBezit;
//    }
//
//
//
//
//}
//
//
