//package edu.rsvier.springmvc.model;
//// Generated May 11, 2015 11:42:12 AM by Hibernate Tools 4.3.1
//
//
//import java.util.Date;
//import javax.persistence.AttributeOverride;
//import javax.persistence.AttributeOverrides;
//import javax.persistence.Column;
//import javax.persistence.EmbeddedId;
//import javax.persistence.Entity;
//import javax.persistence.Table;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;
//
///**
// * PersoonsrolHasTraject generated by hbm2java
// */
//@Entity
//@Table(name="persoonsrol_has_traject"
//    ,catalog="cursisttraject_relatiebeheer"
//)
//public class PersoonsrolHasTraject  implements java.io.Serializable {
//
//
//     private PersoonsrolHasTrajectId id;
//     private Date begindatum;
//     private Date einddatum;
//     private Character succesvolAfgerond;
//
//    public PersoonsrolHasTraject() {
//    }
//
//	
//    public PersoonsrolHasTraject(PersoonsrolHasTrajectId id, Date begindatum) {
//        this.id = id;
//        this.begindatum = begindatum;
//    }
//    public PersoonsrolHasTraject(PersoonsrolHasTrajectId id, Date begindatum, Date einddatum, Character succesvolAfgerond) {
//       this.id = id;
//       this.begindatum = begindatum;
//       this.einddatum = einddatum;
//       this.succesvolAfgerond = succesvolAfgerond;
//    }
//   
//     @EmbeddedId
//
//    
//    @AttributeOverrides( {
//        @AttributeOverride(name="persoonsrolPersoonId", column=@Column(name="persoonsrol_persoon_id", nullable=false) ), 
//        @AttributeOverride(name="persoonsrolRolId", column=@Column(name="persoonsrol_rol_id", nullable=false) ), 
//        @AttributeOverride(name="persoonsrolBegindatum", column=@Column(name="persoonsrol_begindatum", nullable=false, length=10) ), 
//        @AttributeOverride(name="trajectId", column=@Column(name="traject_id", nullable=false) ) } )
//    public PersoonsrolHasTrajectId getId() {
//        return this.id;
//    }
//    
//    public void setId(PersoonsrolHasTrajectId id) {
//        this.id = id;
//    }
//
//    @Temporal(TemporalType.DATE)
//    @Column(name="begindatum", nullable=false, length=10)
//    public Date getBegindatum() {
//        return this.begindatum;
//    }
//    
//    public void setBegindatum(Date begindatum) {
//        this.begindatum = begindatum;
//    }
//
//    @Temporal(TemporalType.DATE)
//    @Column(name="einddatum", length=10)
//    public Date getEinddatum() {
//        return this.einddatum;
//    }
//    
//    public void setEinddatum(Date einddatum) {
//        this.einddatum = einddatum;
//    }
//
//    
//    @Column(name="succesvol_afgerond", length=1)
//    public Character getSuccesvolAfgerond() {
//        return this.succesvolAfgerond;
//    }
//    
//    public void setSuccesvolAfgerond(Character succesvolAfgerond) {
//        this.succesvolAfgerond = succesvolAfgerond;
//    }
//
//
//
//
//}
//
//
