package edu.rsvier.springmvc.model;
// Generated 29-apr-2015 14:52:58 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Traject generated by hbm2java
 */
@Entity
@Table(name = "traject", catalog = "cursisttraject_relatiebeheer"
)
public class Traject implements java.io.Serializable {

    private Integer id;
    private String naam;
    private String omschrijving;
    private Date startdatum;
    private Date sluitingsdatum;
    private Set<Module> modules = new HashSet<Module>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "naam", nullable = false, length = 45)
    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    @Column(name = "omschrijving", length = 65535)
    public String getOmschrijving() {
        return this.omschrijving;
    }

    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "startdatum", length = 10)
    public Date getStartdatum() {
        return this.startdatum;
    }

    public void setStartdatum(Date startdatum) {
        this.startdatum = startdatum;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "sluitingsdatum", length = 10)
    public Date getSluitingsdatum() {
        return this.sluitingsdatum;
    }

    public void setSluitingsdatum(Date sluitingsdatum) {
        this.sluitingsdatum = sluitingsdatum;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "traject", cascade = {CascadeType.ALL})
    public Set<Module> getModules() {
        return this.modules;
    }

    public void setModules(Set<Module> modules) {
        this.modules = modules;
    }
    
    @Override
    public String toString() {
        return ("Traject: "  + this.getNaam() + " : " + this.getOmschrijving() + " " + this.getStartdatum() +  " " + this.getSluitingsdatum());
    }
    
    @Override
    public boolean equals(Object traject2) {
        if(!(traject2 instanceof Traject))
            return false;
        if(this.getId() == (((Traject)traject2).getId()) 
            && this.getNaam().equals(((Traject)traject2).getNaam())
            && this.getStartdatum().equals(((Traject)traject2).getStartdatum())
            && this.getOmschrijving().equals(((Traject)traject2).getOmschrijving()))
            return true;
        else
            return false;
        
    }

}
